### ISSUE TITLE
.

### ISSUE THREAD

**Issue by riky-dev** [viktor111/BH_konsol#1]

**Comment by viktor111** [comment]
netfilterqueue module is giving you problems i had the same thing try running this if you are debian based os. If something else use your package manager.
`sudo apt-get install libnetfilter-queue-dev libnetfilter-queue1`
then 
`pip install NetfilterQueue`

**Comment by RikyRuggi** [comment]
root@kali:~# apt-get install libnetfilter-queue-dev libnetfilter-queue1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnetfilter-queue-dev is already the newest version (1.0.3-1).
libnetfilter-queue1 is already the newest version (1.0.3-1).
0 upgraded, 0 newly installed, 0 to remove and 432 not upgraded.

root@kali:~# pip install NetfilterQueue
Requirement already satisfied: NetfilterQueue in /usr/local/lib/python2.7/dist-packages (0.8.1)

still getting error :(

**Comment by viktor111** [comment]
You can also try to do
` pip3 install NetfilterQueue`
And then try to run it again
